"""The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1+2+3+4+5+6+7=28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1, 3
 6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
21: 1, 3, 7, 21
28: 1, 2, 4, 7, 14, 28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

def next_triangular():
    n = 1
    triangular = 1
    while True:
        yield n, triangular
        n += 1
        triangular += n

def amount_divisors_of(number: int) -> int:
    prime_exponents = {}
    divisor_candidate = 2
    while divisor_candidate * divisor_candidate <= number:
        while number % divisor_candidate == 0:
            prime_exponents[divisor_candidate] = prime_exponents.get(divisor_candidate, 0) + 1
            number //= divisor_candidate
        divisor_candidate += 1
    if number > 1:
        prime_exponents[number] = prime_exponents.get(number, 0) + 1
    divisor_count = 1
    for exponent in prime_exponents.values():
        divisor_count *= exponent + 1
    return divisor_count

def find_first_triangle_with_more_divisors_than(amount_factors_needed: int) -> int:
    triangular_generator = next_triangular()
    while True:
        _, triangular = next(triangular_generator)
        triangular_satisfies_condition = amount_divisors_of(triangular) >= amount_factors_needed
        if triangular_satisfies_condition:
            return triangular


divisors_needed = [5, 50, 500]

for divisors in divisors_needed:
    print(f"The first triangle number with more than {divisors} divisors is...{find_first_triangle_with_more_divisors_than(divisors)}")